### ISSUE TITLE
Questions regarding BuiltinEntityParser for non-space separated languages

### ISSUE THREAD

**Issue by gembin** [snipsco/snips-nlu-ontology#107]
I'm trying to understand how `BuiltinEntityParser` works, and got some questions for `extract_entities` for **non-space separated languages**.  

* Is tokenization required before pass to`BuiltinEntityParser`? I tried it only works if tokenized.
* If i remove the language from [NON_SPACE_SEPARATED_LANGUAGES](https://github.com/snipsco/snips-nlu-ontology/blob/develop/snips-nlu-ontology-parsers/src/utils.rs#L13), it works without tokenization.
* What's the idea of this [part of code](https://github.com/snipsco/snips-nlu-ontology/blob/develop/snips-nlu-ontology-parsers/src/builtin_entity_parser.rs#L125-L139) for non-space separated languages?
If the sentence is not tokenized, the `original_tokens_bytes_ranges` will be `[0..N]`, and `ranges_mapping` will be `{N:0}`, where `N` is the number of bytes. And the result for `extract_entities` will be empty.
* This [code comment](https://github.com/snipsco/snips-nlu-ontology/blob/develop/snips-nlu-ontology-parsers/src/utils.rs#L21) for `get_ranges_mapping` should be **ends**  instead of **starts**?

Thanks!

**Comment by ClemDoum** [comment]
Hi @gembin :
Tokenization is not required for the the **non-space separated languages**. However `Rustling` that does the actual parsing does not handle mixed strings where most tokens are not separated but some are. In Japanese for instance you can have some spaces in a mostly non space separated sentence. 

What we do in the part of code that you pointed out is to remove all spaces from the input string and then pass it to `Rustling`. We pass a regex on the sentence to split it character by character (what we call a token). 

As `Rustling` operates on the bytes with removed spaces will output invalid ranges, that's why we need to keep a mapping between bytes in the string without spaces and tokens indexes (characters indexes in the original string).

The comment is right: if token 5 end at the 65th byte of the joined string, this means that token 6 starts at the 65th byte of the joined string.

I hope it helps !

**Comment by gembin** [comment]
@ClemDoum thanks for your detailed explanation.

The problem is it doesn't work if without tokenization for non-space separated language like JA. Take the following sentence as example, I just used google translation to translate the sentence from EN to JA. And expecting the `来週に`=`next week` should be extracted as `Time` entity, but nothing is extracted.

EN: `I will travel to Japan next week`
JA: `私は来週に日本に行きます`

If i remove `JA` from `NON_SPACE_SEPARATED_LANGUAGES`, which means it considered JA as space-separated language, it extracted the  `来週に` as `Time` entity as expected.

**Comment by ClemDoum** [comment]
@gembin sorry, my first reponse was incorrect.

You do need to provide sentences where tokens are space separated for all languages in this library.
Rustling needs inputs without spaces for languages in NON_SPACE_SEPARATED_LANGUAGES, and tokens separated by spaces for the other languages.

If you want to parse builtin entities directly on original `JA` sentence (without space) I would recommend either tokenizing them beforehand or to use directly Rustling on the original sentence (no tokenization required).

Sorry again for my incorrect answer.

**Comment by gembin** [comment]
@ClemDoum thanks a lot! It's much clear. 👍 
One more question, will the pre-tokenizing result affect the result of entity extraction?

**Comment by ClemDoum** [comment]
@gembin yes.

For instance in what you detailed earlier Rustling was correctly catching the `next week` words in the sentence. However because of [this condition](https://github.com/snipsco/snips-nlu-ontology/blob/4fe86e00211ec8402ea1a437dc7e7a1d1c7e59c8/snips-nlu-ontology-parsers/src/builtin_entity_parser.rs#L147-L148), the match is discarded if the ranges found by Rustling don't match tokens ranges

**Comment by ClemDoum** [comment]
However if you tokenize each character separately then what I just described should not happen.

**Comment by gembin** [comment]
thanks!
